name = "MyST"
uuid = "8956771c-59f6-4c53-8c30-0cafefe57311"
authors = ["Joe Carpinelli <jdcarpinelli@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
DocStringExtensions = "0.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
